In [1]:
import numpy as np
import cv2
import os
import matplotlib as plt
import random

In [2]:
txtpath = 'path'
signs = ['hello', 'sign', 'no', 'understand'] #... add the signs you have ...
handlandmarks = []
signlandmarks = []
training_data = []
i = 0
#for each folder we take the path and set an index for the sign
for sign in signs:
    #try:
    path = os.path.join(txtpath, sign)
    sign_num = signs.index(sign)
    print(sign)
    #for each txt file we open it, read it and create the training data
    for txt in os.listdir(path):
        #try:
        #print(txt)
        with open(path+'/'+txt, 'r') as reader:
            #for each line in the txt file (there is only one)
            for line in reader:
                #for each number in the line we build the list of points for the landmarks
                for number in line.split():
                    if i < 84:
                        handlandmarks.append(round(float(number),3))
                        i = i + 1
                    else:
                        signlandmarks.append(handlandmarks)
                        handlandmarks = []
                        i = 0
        signlandmarks = np.asarray(signlandmarks)
        if signlandmarks.shape[0] >= 20:
            signlandmarks = signlandmarks[0:20]
            training_data.append([signlandmarks, sign_num])
            #print(signlandmarks.shape)
        signlandmarks = []
        #except:
         #   pass
    #except:
     #   pass
print(len(training_data))

print('FINISHED')

hello
sign
2794
FINISHED


In [3]:
random.shuffle(training_data)
zero = 0
one = 0
two = 0
three = 0
for sign in training_data:
    if sign[1] == 0:
        zero = zero + 1
    if sign[1] == 1:
        one = one + 1
    if sign[1] == 2:
        two = two + 1
    if sign[1] == 3:
        three = three + 1
    print(sign[1])
print('There are',zero,'zeros,',one,'ones,',two,'twos and',three,'threes')

1
1
1
0
0
0
0
1
1
0
1
0
1
0
1
0
1
0
0
1
1
0
1
1
0
0
1
0
1
1
0
0
1
0
1
1
1
1
1
1
1
0
1
1
1
1
0
0
1
1
1
1
0
1
0
1
1
1
0
0
1
1
1
0
1
0
0
1
1
1
1
1
1
1
1
0
1
1
1
0
0
1
1
1
0
1
1
1
0
1
0
0
1
0
0
0
1
0
0
1
0
0
0
0
1
0
1
0
1
1
0
1
1
1
0
0
1
0
0
1
0
1
1
0
0
0
0
1
1
0
0
1
1
0
0
1
0
0
1
0
1
0
0
0
0
0
0
0
0
0
1
1
0
1
1
0
1
0
0
1
0
0
0
1
1
1
1
1
0
1
0
0
0
1
0
0
1
0
1
0
0
1
0
0
0
1
1
0
1
0
1
0
1
0
0
0
1
1
1
0
1
0
1
1
0
1
0
1
1
1
0
0
1
1
0
1
0
0
1
1
0
0
1
0
0
0
1
1
0
1
1
1
0
1
1
1
1
0
1
0
1
1
0
1
1
0
1
0
1
0
0
1
1
1
0
0
0
1
1
1
1
0
0
1
0
1
0
0
1
1
0
0
1
0
0
0
0
0
0
1
0
1
1
0
1
1
1
1
1
1
1
0
1
1
1
1
1
0
0
1
0
0
0
0
0
1
1
1
0
1
0
1
1
1
1
0
0
1
1
1
0
0
0
1
0
0
0
1
1
0
0
1
1
1
1
1
1
1
1
0
0
1
1
1
0
1
1
0
1
1
1
1
0
1
1
1
1
1
0
1
1
0
0
1
0
0
1
1
1
0
1
1
1
1
0
0
1
1
0
0
1
1
0
0
0
0
0
1
0
0
1
0
1
0
0
1
1
0
0
1
1
1
1
0
1
1
1
1
1
1
0
0
0
1
0
1
1
1
1
0
1
1
0
1
1
0
0
0
1
0
1
1
0
1
0
0
1
0
1
1
1
1
1
1
1
0
1
1
1
1
0
1
1
0
0
0
1
0
0
0
1
1
0
0
1
1
0
1
1
0
1
1
1
0
1
0
0
1
0
0
1
1
1
1
1
1
1
0
0
1
1
1
0
1
1
1
1
0
0
0


In [4]:
#Specification of how we want to use the data
X = []
Y = []

for landmarks, sign in training_data:
    X.append(landmarks)
    Y.append(sign)
    
X = np.array(X).reshape(-1, 20, 84)
Y = np.array(Y)
print(X)
print(Y)

[[[0.295 0.566 0.367 ... 0.379 0.429 0.378]
  [0.375 0.459 0.399 ... 0.429 0.38  0.408]
  [0.459 0.397 0.451 ... 0.382 0.415 0.377]
  ...
  [0.51  0.723 0.489 ... 0.7   0.466 0.697]
  [0.735 0.486 0.732 ... 0.468 0.693 0.51 ]
  [0.486 0.738 0.478 ... 0.683 0.512 0.731]]

 [[0.848 0.705 0.853 ... 0.726 0.975 0.747]
  [0.747 0.963 0.74  ... 0.972 0.742 0.948]
  [0.963 0.73  0.967 ... 0.732 0.949 0.725]
  ...
  [0.462 0.786 0.434 ... 0.777 0.426 0.782]
  [0.772 0.431 0.791 ... 0.476 0.752 0.481]
  [0.456 0.769 0.439 ... 0.61  0.423 0.608]]

 [[0.374 0.703 0.388 ... 0.642 0.543 0.647]
  [0.675 0.358 0.633 ... 0.484 0.801 0.355]
  [0.361 0.637 0.38  ... 0.816 0.354 0.684]
  ...
  [0.53  0.4   0.581 ... 0.422 0.511 0.43 ]
  [0.407 0.554 0.422 ... 0.498 0.444 0.493]
  [0.541 0.433 0.537 ... 0.463 0.499 0.427]]

 ...

 [[0.615 0.434 0.639 ... 0.    0.    0.   ]
  [0.    0.    0.    ... 0.    0.    0.   ]
  [0.    0.    0.    ... 0.844 0.506 0.829]
  ...
  [0.859 0.572 0.648 ... 0.291 0.856 0.2

In [5]:
import pickle

#Save the data
pickle_out = open("x_database.pickle","wb")
pickle.dump(X, pickle_out)
pickle_out.close()

In [6]:
pickle_out = open("y_database.pickle","wb")
pickle.dump(Y, pickle_out)
pickle_out.close()